version: '3.8'

services:
  proxy:
    image: nginx:mainline
    restart: always
    ports:
      - "80:80"
    networks:
      - local
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
